package pt.isel.pdm.jht.profslist

data class Prof(val code: Int, val name: String, val email: String)

object Profs {

    val profs = arrayOf(
            Prof(1647, "Carlos Guedes",	"cguedes@cc.isel.ipl.pt"),
            Prof(1754, "João Trindade",	"jtrindade@cc.isel.ipl.pt"),
            Prof(440, "Luís Osório", "aosorio@deetc.isel.ipl.pt"),
            Prof(445, "António Couto Pinto", "amcp@cedet.isel.ipl.pt"),
            Prof(465, "Carlos Martins", "cmartins@cc.isel.ipl.pt"),
            Prof(564, "José Paraizo", "paraiso@cc.isel.ipl.pt"),
            Prof(593, "João Florêncio", "jflorencio@deetc.isel.ipl.pt"),
            Prof(598, "Manuel Carvalho", "mcarvalho@deetc.isel.ipl.pt"),
            Prof(604, "Manuel Barata", "mmb@isel.ipl.pt"),
            Prof(639, "Mário Araújo", "maraujo@deetc.isel.ipl.pt"),
            Prof(663, "Valentim Correia", "vmcorreia@deetc.isel.ipl.pt"),
            Prof(668, "Walter Vieira", "wv@deetc.isel.ipl.pt"),
            Prof(690, "Fernando Sousa", "fsousa@cc.isel.ipl.pt"),
            Prof(691, "Helder Pita", "hpita@deetc.isel.ipl.pt"),
            Prof(697, "Jorge Martins", "jmartins@cc.isel.ipl.pt"),
            Prof(710, "Luís Assunção", "lass@isel.ipl.pt"),
            Prof(715, "Manuela Sousa", "msousa@cc.isel.ipl.pt"),
            Prof(718, "Mário Pinheiro", "mpinheiro@cc.isel.ipl.pt"),
            Prof(726, "Vitor Almeida", "valmeida@deetc.isel.ipl.pt"),
            Prof(754, "Ezequiel Conde", "ezeq@cc.isel.ipl.pt"),
            Prof(798, "Vitor Silva", "vsilva@cc.isel.ipl.pt"),
            Prof(818, "Mário Simões", "msimoes@cc.isel.ipl.pt"),
            Prof(877, "Jorge Fonseca", "jfonseca@cc.isel.ipl.pt"),
            Prof(889, "Pedro Pereira", "palex@cc.isel.ipl.pt"),
            Prof(899, "Hernâni Mergulhão", "hernani@cc.isel.ipl.pt"),
            Prof(958, "Miguel Campilho", "mpcg@cedet.isel.ipl.pt"),
            Prof(999, "CAE A3ES", "a3es@deetc.isel.ipl.pt"),
            Prof(1070, "Nuno Oliveira", "no@deetc.isel.ipl.pt"),
            Prof(1207, "Pedro Félix", "pedrofelix@cc.isel.ipl.pt"),
            Prof(1231, "João Ferreira", "jferreira@deetc.isel.ipl.pt"),
            Prof(1238, "David Coutinho", "davidpc@cc.isel.ipl.pt"),
            Prof(1242, "Pedro Sampaio", "psampaio@cc.isel.ipl.pt"),
            Prof(1245, "Luís Falcão", "lfalcao@cc.isel.ipl.pt"),
            Prof(1253, "Pedro Ribeiro", "pribeiro@deetc.isel.ipl.pt"),
            Prof(1281, "Nuno Cota", "ncota@deetc.isel.ipl.pt"),
            Prof(1288, "Paulo Araújo", "paraujo@deetc.isel.ipl.pt"),
            Prof(1319, "Porfirio Filipe", "pfilipe@deetc.isel.ipl.pt"),
            Prof(1367, "João Pedro Patriarca", "jpatri@cc.isel.ipl.pt"),
            Prof(1369, "Paulo Pereira", "palbp@cc.isel.ipl.pt"),
            Prof(1370, "José Aguilar", "jaguilar@adm.isel.ipl.pt"),
            Prof(1375, "Artur Ferreira", "arturj@cc.isel.ipl.pt"),
            Prof(1402, "António Teófilo", "ateofilo@deetc.isel.ipl.pt"),
            Prof(1408, "Matilde Pato", "mpato@deetc.isel.ipl.pt"),
            Prof(1472, "Alessandro Fantoni", "afantoni@deetc.isel.ipl.pt"),
            Prof(1474, "Nuno Datia", "datia@isel.ipl.pt"),
            Prof(1548, "João Viegas", "jviegas@net.ipl.pt"),
            Prof(1550, "Nuno Leite", "nleite@cc.isel.ipl.pt"),
            Prof(1551, "José Simão", "jsimao@cc.isel.ipl.pt"),
            Prof(1552, "Pedro Fazenda", "pvf@cedet.isel.ipl.pt"),
            Prof(1601, "Afonso Remédios", "aremedios@deetc.isel.ipl.pt"),
            Prof(1604, "Filipe Freitas", "ffreitas@cc.isel.ipl.pt"),
            Prof(1619, "Miguel Gamboa Carvalho", "mcarvalho@cc.isel.ipl.pt"),
            Prof(1621, "Pedro Miguens", "pmiguens@cc.isel.ipl.pt"),
            Prof(1636, "Nelson Costa", "ncosta@deetc.isel.ipl.pt"),
            Prof(1686, "Cátia Vaz", "cvaz@cc.isel.ipl.pt"),
            Prof(1687, "Rui Joaquim", "rjoaquim@deetc.isel.ipl.pt"),
            Prof(1696, "Lara Santos", "lsantos@deetc.isel.ipl.pt"),
            Prof(1725, "Fernando Nunes", "fnunes@cc.isel.ipl.pt"),
            Prof(1736, "João Ascenso", "jascenso@deetc.isel.ipl.pt"),
            Prof(1737, "Mário Véstias", "mvestias@deetc.isel.ipl.pt"),
            Prof(1740, "Vítor Fialho", "vfialho@deetc.isel.ipl.pt"),
            Prof(1743, "Tiago Dias", "tdias@cc.isel.ipl.pt"),
            Prof(1755, "André Lourenço", "arlourenco@deetc.isel.ipl.pt"),
            Prof(1896, "Paula Graça", "mgraca@deetc.isel.ipl.pt"),
            Prof(1911, "Guilherme Figueiredo", "gfigueiredo@cc.isel.ipl.pt"),
            Prof(1912, "Ivo Rodrigues", "iarodrigues@deetc.isel.ipl.pt"),
            Prof(1980, "Diogo Cardoso", "dcardoso@cc.isel.ipl.pt"),
            Prof(1984, "João Silva", "jsilva@deetc.isel.ipl.pt"),
            Prof(9500, "Sofia Azevedo", "sazevedo@cc.isel.ipl.pt"),
            Prof(12920, "Luis Fernandes", "mfernandes@deetc.isel.ipl.pt")
    )

}